pom.xml
src/main/java/org/semver4j/Semver.java
src/test/java/org/semver4j/SemverTest.java

Handle invalid version (closes #4)

---

src/main/java/org/semver4j/Semver.java
src/main/java/org/semver4j/parsers/OtherSemverParser.java
src/main/java/org/semver4j/parsers/ParsedVersion.java
src/main/java/org/semver4j/parsers/SemverParser.java
src/main/java/org/semver4j/parsers/StrictSemverParser.java
src/test/java/org/semver4j/SemverTest.java
src/test/java/org/semver4j/parsers/StrictSemverParserTest.java

Introduced two types of parsers
* `StrictSemverParser` - this parser strictly follows semver rules
* `OtherSemverParser` - match any other rules
Resolves #6

Refactor version parsers

---

src/test/java/org/semver4j/SemverTest.java

Add test case to close issue #27

---

src/test/java/org/semver4j/NpmSemverTest.java

Add test case to close issue #30

---

src/test/java/org/semver4j/internal/range/RangesListFactoryTest.java

Add test case to close issue #31

---

src/test/java/org/semver4j/SemverTest.java

Add test case to close issue #33

---

src/test/java/org/semver4j/SemverTest.java

Add test case to close issue #35

---

src/test/java/org/semver4j/SemverTest.java

Add test case to close issue #37

---

src/test/java/org/semver4j/SemverTest.java

Add test case to close issue #38

---

src/test/java/org/semver4j/NpmSemverTest.java

Add test case to close issue #26

---

src/main/java/org/semver4j/Semver.java
src/test/java/org/semver4j/SemverTest.java

Add isValid method

---

.github/workflows/ci.yml
pom.xml

Add codecov and JaCoCo support

---

.github/release-drafter.yml

Handle `refactor` label to store in release notes.

Add `refactor` label handling.

---

.github/workflows/release.yml
pom.xml

Fix creating artifact with version in Maven Central

---

README.md
src/main/java/org/semver4j/internal/Tokenizers.java
src/main/java/org/semver4j/internal/range/processor/CaretProcessor.java
src/main/java/org/semver4j/internal/range/processor/GreaterThanOrEqualZeroProcessor.java
src/main/java/org/semver4j/internal/range/processor/HyphenProcessor.java
src/main/java/org/semver4j/internal/range/processor/IvyProcessor.java
src/main/java/org/semver4j/internal/range/processor/Processor.java
src/main/java/org/semver4j/internal/range/processor/RangesUtils.java
src/main/java/org/semver4j/internal/range/processor/TildeProcessor.java
src/main/java/org/semver4j/internal/range/processor/XRangeProcessor.java
src/test/java/org/semver4j/internal/range/processor/CaretProcessorTest.java
src/test/java/org/semver4j/internal/range/processor/GreaterThanOrEqualZeroProcessorTest.java

Add Javadoc and cleanup processors

---

.github/workflows/ci.yml
.github/workflows/release.yml

This reduce a manual work connected with changing versions after release.

Automatically update versions in README.md after release

---

README.md
src/main/java/org/semver4j/Semver.java
src/main/java/org/semver4j/internal/Differ.java
src/test/java/org/semver4j/SemverTest.java

Rename `SUFFIX` to `PRE_RELEASE`

---

src/main/java/org/semver4j/RangesListFactory.java
src/main/java/org/semver4j/Semver.java
src/test/java/org/semver4j/RangesListFactoryTest.java

We should keep this class close to `RangesList`.

Move `RangesListFactory` from internal to root package

---

.github/workflows/release.yml

We should checkout code in each job.

Fix GitHub workflow

---

src/main/java/org/semver4j/Range.java
src/main/java/org/semver4j/RangesList.java
src/main/java/org/semver4j/Semver.java
src/main/java/org/semver4j/internal/range/processor/GreaterThanOrEqualZeroProcessor.java
src/test/java/org/semver4j/RangeTest.java
src/test/java/org/semver4j/RangesListFactoryTest.java

These convenience methods check whether a range was created in such a way that it matches any version.

Add `isSatisfiedByAny()` to `Range` and `RangesList`

---

src/main/java/org/semver4j/RangesList.java

Fix wrong example in the `RangesList` java doc.
Connected with #112

Polishing of documentation

---

src/main/java/org/semver4j/RangesList.java
src/test/java/org/semver4j/RangesListFactoryTest.java
src/test/java/org/semver4j/RangesListTest.java

Please have a look at the individual commit messages for the details.

RangesList improvements

---

src/main/java/org/semver4j/RangesListFactory.java
src/test/java/org/semver4j/RangesListFactoryTest.java

Transletes range:
```
<=   2.6.8 ||    >= 3.0.0 <= 3.0.1 || >5.0.0
```
to
```
<=2.6.8 || >=3.0.0 <=3.0.1 || >5.0.0
```

Strip whitespaces between range operator

---

src/main/java/org/semver4j/Semver.java
src/test/java/org/semver4j/SemverTest.java

Please have a look at the individual commit messages for the details.

Add an `isApiCompatible()` convenience `Semver` function

---

pom.xml
src/main/java/org/semver4j/Range.java
src/main/java/org/semver4j/RangesExpression.java
src/main/java/org/semver4j/RangesList.java
src/main/java/org/semver4j/RangesListFactory.java
src/main/java/org/semver4j/RangesString.java
src/main/java/org/semver4j/Semver.java
src/main/java/org/semver4j/internal/Coerce.java
src/main/java/org/semver4j/internal/Comparator.java
src/main/java/org/semver4j/internal/Differ.java
src/main/java/org/semver4j/internal/Modifier.java
src/main/java/org/semver4j/internal/StrictParser.java
src/main/java/org/semver4j/internal/Tokenizers.java
src/main/java/org/semver4j/internal/range/RangeProcessorPipeline.java
src/main/java/org/semver4j/internal/range/processor/CaretProcessor.java
src/main/java/org/semver4j/internal/range/processor/GreaterThanOrEqualZeroProcessor.java
src/main/java/org/semver4j/internal/range/processor/HyphenProcessor.java
src/main/java/org/semver4j/internal/range/processor/IvyProcessor.java
src/main/java/org/semver4j/internal/range/processor/Processor.java
src/main/java/org/semver4j/internal/range/processor/RangesUtils.java
src/main/java/org/semver4j/internal/range/processor/TildeProcessor.java
src/main/java/org/semver4j/internal/range/processor/XRangeProcessor.java

Added nullable and not nullable annotations by jetbrains

Feature: Nullable annotations

---

pom.xml

See issue https://github.com/semver4j/semver4j/issues/180

Fix JetBrains annotations scope to provided

---

README.md
src/main/java/org/semver4j/Semver.java
src/test/java/org/semver4j/SemverTest.java

Introduce formatter methods to customize version output

---

.github/workflows/ci.yml
.mvn/nullaway.jvm.config
pom.xml

Related: https://github.com/semver4j/semver4j/issues/312
Changes in this PR:
- A new Maven profile `nullaway` added
- Analysis with Java 23 added to the CI - the latest version of java contains the most fixes

Add NullAway checks

---

.github/workflows/ci.yml
src/main/java/org/semver4j/RangesListFactory.java
src/main/java/org/semver4j/RangesString.java
src/main/java/org/semver4j/internal/RangeProcessorPipeline.java
src/main/java/org/semver4j/processor/AllVersionsProcessor.java
src/main/java/org/semver4j/processor/CaretProcessor.java
src/main/java/org/semver4j/processor/GreaterThanOrEqualZeroProcessor.java
src/main/java/org/semver4j/processor/HyphenProcessor.java
src/main/java/org/semver4j/processor/IvyProcessor.java
src/main/java/org/semver4j/processor/Processor.java
src/main/java/org/semver4j/processor/RangesUtils.java
src/main/java/org/semver4j/processor/TildeProcessor.java
src/main/java/org/semver4j/processor/XRangeProcessor.java
src/test/java/org/semver4j/RangesListFactoryTest.java
src/test/java/org/semver4j/internal/RangeProcessorPipelineTest.java
src/test/java/org/semver4j/processor/AllVersionsProcessorTest.java
src/test/java/org/semver4j/processor/CaretProcessorTest.java
src/test/java/org/semver4j/processor/GreaterThanOrEqualZeroProcessorTest.java
src/test/java/org/semver4j/processor/HyphenProcessorTest.java
src/test/java/org/semver4j/processor/IvyProcessorTest.java
src/test/java/org/semver4j/processor/ProcessorTest.java
src/test/java/org/semver4j/processor/TildeProcessorTest.java
src/test/java/org/semver4j/processor/XRangeProcessorTest.java

Please have a look at the individual commit messages for the details.

Allow to configure processors
